[package]
name = "sentry-types"
version = "0.3.0"
license = "Apache-2.0"
description = "Common reusable types for implementing the sentry.io protocol."
homepage = "https://sentry.io/"
repository = "https://github.com/getsentry/rust-sentry-types"
documentation = "https://docs.rs/sentry-types"
keywords = ["sentry", "protocol"]
readme = "README.md"
authors = ["Sentry <hello@sentry.io>"]
exclude = [
    ".vscode/**/*",
    "scripts/**/*"
]

[badges]
travis-ci = { repository = "getsentry/rust-sentry-types" }

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"
url = "1.7.0"
serde = "1.0.36"
serde_derive = "1.0.36"
serde_json = { version = "1.0", features = ["preserve_order"] }
url_serde = "0.2.0"
chrono = { version = "0.4.0", features = ["serde"] }
uuid = { version = "0.6.2", features = ["serde", "v4"] }
linked-hash-map = { version = "0.5.1", features = ["serde_impl"] }
debugid = { version = "0.1.0", features = ["with_serde"] }
